departamento/urls.py
from django.urls import path
from . import views

app_name = "departamento"
urlpatterns = [
    path("hola_mundo/", views.hola_mundo, name="hola_mundo"),

    path("", views.departamentos, name="departamentos"),
    path("<int:id>/", views.ver_departamento, name="ver_departamento"),
    #nuevo
    path("nuevo/", views.nuevo_dpto, name="nuevo_dpto"),
    path("<int:id>/editar/", views.editar_departamento, name="editar_departamento"),
    #editar departamettno
    path("prueba_base/", views.prueba_base, name="prueba_base")
]

empleado/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.empleados, name="empleados")
]

empresa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("departamento/", include("departamento.urls")),
    path("empleado/", include("empleado.urls")),
    path("perfil/", include("perfil.urls"))
]

perfil/urls.py
from django.urls import path
from . import views

app_name = "perfil"
urlpatterns = [
    path("login/", views.iniciar_sesion, name="login"),
    path("logout/", views.cerrar_sesion, name="logout"),
]

departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    nombre = models.CharField(max_length = 50, unique=True)

    def __str__(self):
        return "departamento: " + self.nombre

    def sueldo_total(self):

        empleados = self.empleado_set.all()
        total = 0
        for emp in empleados:
            total += emp.sueldo
        return total

empleado/models.py
from django.db import models
from departamento.models import Departamento
# Create your models here.

class Empleado(models.Model):
    nombre = models.CharField(max_length = 50)
    apellido = models.CharField(max_length = 50, null=True)
    nacimiento = models.DateField()
    sueldo = models.DecimalField(max_digits=10, decimal_places=2)
    departamento = models.ForeignKey(Departamento,
        on_delete=models.SET_NULL,
        null=True)

perfil/models.py
from django.db import models

# Create your models here.

departamento/forms.py
from django import forms
from .models import Departamento

class DepartamentoForm(forms.ModelForm):
    class Meta:
        model = Departamento
        fields = "__all__"

departamento/views.py
from django.shortcuts import render, HttpResponse, Http404, get_object_or_404,redirect
from .models import Departamento
from .forms import DepartamentoForm

from django.contrib.auth.decorators import login_required
# Create your views here.
def hola_mundo(request):
    #return HttpResponse("Hola Mundo")
    template = "departamento/hola_mundo.html"
    contexto = {
        "nombre":"Pedro",
        "numero":1234
    }
    return render(request, template, contexto)

def departamentos(request):
    departamentos = Departamento.objects.all()

    template = "departamento/departamentos.html"
    contexto = {
        "lista_dptos":departamentos,
    }
    return render(request, template, contexto)


def ver_departamento(request, id):
    try:
        dpto = Departamento.objects.get(pk=id)
    except Departamento.DoesNotExist:
        raise Http404("no se encontró")

    #dpto = get_object_or_404(Departamento, pk=id)

    #dpto.empleado_set.all()
    template = "departamento/departamento.html"
    contexto = {
        "dpto":dpto,
    }
    return render(request, template, contexto)

@login_required
def nuevo_dpto(request):
    print(request.POST)
    form = DepartamentoForm()
    if request.method == "POST":
        form = DepartamentoForm(request.POST)
        if form.is_valid():
            dpto = form.save()
            return redirect("departamento:ver_departamento", dpto.id)

    contexto = {"form":form}
    template = "departamento/nuevo.html"
    return render(request, template, contexto)


def editar_departamento(request,id):
    try:
        dpto = Departamento.objects.get(pk=id)
    except Departamento.DoesNotExist:
        raise Http404("no se encontró")

    if request.method == "GET":
        form = DepartamentoForm(instance=dpto)

    if request.method == "POST":
        form = DepartamentoForm(request.POST, instance=dpto)
        if form.is_valid():
            dpto = form.save()
            return redirect("departamento:ver_departamento", dpto.id)    


    template = "departamento/nuevo.html"
    contexto = {"form":form}
    return render(request, template, contexto)


def prueba_base(request):
    return render(request, "base.html", {})

empleado/views.py
from django.shortcuts import render, HttpResponse
from .models import Empleado
# Create your views here.
def empleados(request):
    lista_empleados = Empleado.objects.all()
    return render(request, "empleado/empleados.html",{"lista_empleados":lista_empleados})

perfil/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout

def iniciar_sesion(request):
    siguiente = request.GET.get("next","departamento:hola_mundo")
    form = AuthenticationForm()

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return redirect(siguiente)

    template = "perfil/login.html"
    contexto = {"form":form}
    return render(request, template, contexto)

def cerrar_sesion(request):
    logout(request)
    return redirect("departamento:hola_mundo")

departamento/templates/departamento/departamento.html
{% extends 'base.html' %}

{% block title %}
    {{dpto.nombre}}
{% endblock %}

{% block contenido %}
    <h2>Departamento: {{dpto.nombre}}</h2>
    <p>id: {{dpto.id}}</p>
    ñá
    <h2>Empleados: {{dpto.empleado_set.all.count}}</h2>
    {% include 'empleado/listado_empleados.html' with lista_empleados=dpto.empleado_set.all %}
    <h2>SUeldos TOTAL: {{dpto.sueldo_total}}</h2>
{% endblock %}

departamento/templates/departamento/departamentos.html
{% extends 'base.html' %}

{% block title %}
    departamentos
{% endblock %}

{% block contenido %}
<h1>Departamentos: {{ lista_dptos.count }}</h1>
{% for dpto in lista_dptos %}
    <a href="{% url 'departamento:ver_departamento' dpto.id %}">Ir al dpto</a>
    <p>{{ dpto.nombre }} - id: {{dpto.id}}</p>
    {{ forloop.counter }}
{% endfor %}

{% if lista_dptos.count > 2 %}
    <h2>HAY MAS DE dos Departamentos</h2>
{% else %}
    <h2>NO HAY MAS DE dos Departamentos</h2>
{% endif %}
{% endblock %}

departamento/templates/departamento/hola_mundo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hola</title>
</head>
<body>
    <h1>Hola mundo</h1>
    <p>
        {{ nombre }}
    </p>
    <p>
        {{ numero }}
    </p>
</body>
</html>

departamento/templates/departamento/nuevo.html
{% extends 'base.html' %}
{% block title %}
    nuevo dpto
{% endblock %}
{% block contenido%}
    crear departamento
    <form action="" method="POST">
        {% csrf_token %}
        <div>
            {{ form.nombre.label }}
            {{ form.nombre }}
            {{ form.nombre.errors }}
        </div>
        <div>
            {{form.errors}}
        </div>
        <input type="submit" value="CREAR">
    </form>
{% endblock %}

empleado/templates/empleado/empleados.html
{% extends 'base.html' %}

{%block contenido%}
    {% include 'empleado/listado_empleados.html'%}
{%endblock%}

empleado/templates/empleado/listado_empleados.html
<h2>Empleados</h2>
<ul>
    {% for emp in lista_empleados %}
        <li>
            {{ emp.nombre }}

        </li>
    {% endfor %}
</ul>

perfil/templates/perfil/login.html
{% extends 'base.html' %}

{% block title %}
    Iniciar sesión
{% endblock %}

{% block contenido %}

    <form method="POST">
        {% csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Iniciar sesion">
    </form>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <header>
        {% include 'navbar.html' %}
    </header>
    <div>
        <img src="{% static 'img/empresa.jpeg' %}" alt="empresa">
    </div>
    <div>
        {% block contenido %}
        {% endblock %}
    </div>
    <footer>mi footer</footer>

</body>
</html>

templates/navbar.html
<nav>
    <a href="#">Inicio</a>
    <a href="#">Empleados</a>
    <a href="#">Departamentos</a>
    {% if request.user.is_authenticated %}
        <a href="{% url 'perfil:logout' %}">Cerrar sesión</a>
    {% else %}
        <a href="{% url 'perfil:login' %}">Iniciar sesión</a>
    {% endif %}
</nav>